//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Export_Table = new HashSet<Export_Table>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Customer_Phone { get; set; }
        public Nullable<int> Customer_Mobile { get; set; }
        public string Customer_Fax { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Export_Table> Export_Table { get; set; }
    }
}
