//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Table
    {
        public int Emp_ID { get; set; }
        public int Customer_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Export_Number { get; set; }
        public Nullable<System.DateTime> Export_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Supplier_Name { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
