//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_Table
    {
        public int Emp_ID { get; set; }
        public int Supplier_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Import_Number { get; set; }
        public Nullable<System.DateTime> Import_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
