//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Import_Table = new HashSet<Import_Table>();
        }
    
        public int Supplier_ID { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<int> Supplier_Phone { get; set; }
        public Nullable<int> Supplier_Mobile { get; set; }
        public string Supplier_Fax { get; set; }
        public string Supplier_Email { get; set; }
        public string Supplier_WebSite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Import_Table> Import_Table { get; set; }
    }
}
