//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Werehouse_Product
    {
        public int WH_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Transfare_from { get; set; }
        public Nullable<int> Transfare_to { get; set; }
        public Nullable<System.DateTime> Transfare_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Quantity_Transfared { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
